// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	GetUserInfoRequest
	GetUserInfoResponse
*/
package api

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserInfoRequest struct {
	Authorization string `protobuf:"bytes,1,opt,name=authorization" json:"authorization,omitempty"`
}

func (m *GetUserInfoRequest) Reset()                    { *m = GetUserInfoRequest{} }
func (m *GetUserInfoRequest) String() string            { return proto1.CompactTextString(m) }
func (*GetUserInfoRequest) ProtoMessage()               {}
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetUserInfoResponse struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UserName string `protobuf:"bytes,2,opt,name=user_name,json=userName" json:"user_name,omitempty"`
}

func (m *GetUserInfoResponse) Reset()                    { *m = GetUserInfoResponse{} }
func (m *GetUserInfoResponse) String() string            { return proto1.CompactTextString(m) }
func (*GetUserInfoResponse) ProtoMessage()               {}
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto1.RegisterType((*GetUserInfoRequest)(nil), "proto.GetUserInfoRequest")
	proto1.RegisterType((*GetUserInfoResponse)(nil), "proto.GetUserInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for GipfeliAuthService service

type GipfeliAuthServiceClient interface {
	GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
}

type gipfeliAuthServiceClient struct {
	cc *grpc.ClientConn
}

func NewGipfeliAuthServiceClient(cc *grpc.ClientConn) GipfeliAuthServiceClient {
	return &gipfeliAuthServiceClient{cc}
}

func (c *gipfeliAuthServiceClient) GetUserInfo(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	out := new(GetUserInfoResponse)
	err := grpc.Invoke(ctx, "/proto.GipfeliAuthService/GetUserInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GipfeliAuthService service

type GipfeliAuthServiceServer interface {
	GetUserInfo(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
}

func RegisterGipfeliAuthServiceServer(s *grpc.Server, srv GipfeliAuthServiceServer) {
	s.RegisterService(&_GipfeliAuthService_serviceDesc, srv)
}

func _GipfeliAuthService_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GipfeliAuthServiceServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GipfeliAuthService/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GipfeliAuthServiceServer).GetUserInfo(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GipfeliAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GipfeliAuthService",
	HandlerType: (*GipfeliAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserInfo",
			Handler:    _GipfeliAuthService_GetUserInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x56, 0x5c, 0x42, 0xee, 0xa9,
	0x25, 0xa1, 0xc5, 0xa9, 0x45, 0x9e, 0x79, 0x69, 0xf9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0x2a, 0x5c, 0xbc, 0x20, 0xa5, 0xf9, 0x45, 0x99, 0x55, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0xa8, 0x82, 0x4a, 0xde, 0x5c, 0xc2, 0x28, 0x7a, 0x8b, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xc4, 0xb9, 0xd8, 0x4b, 0x81, 0x62, 0xf1, 0x99, 0x29, 0x50, 0x6d,
	0x6c, 0x20, 0xae, 0x67, 0x8a, 0x90, 0x34, 0x17, 0x27, 0x58, 0x22, 0x2f, 0x31, 0x37, 0x55, 0x82,
	0x09, 0x2c, 0xc5, 0x01, 0x12, 0xf0, 0x03, 0xf2, 0x8d, 0xa2, 0x80, 0x0e, 0xc9, 0x2c, 0x48, 0x4b,
	0xcd, 0xc9, 0x74, 0x04, 0x5a, 0x12, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0xe4, 0xc2, 0xc5,
	0x8d, 0x64, 0x85, 0x90, 0x24, 0xc4, 0xf1, 0x7a, 0x98, 0x4e, 0x96, 0x92, 0xc2, 0x26, 0x05, 0x71,
	0x51, 0x12, 0x1b, 0x58, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x58, 0x46, 0x09, 0x61, 0x00,
	0x01, 0x00, 0x00,
}
